# DRoL

In [1]:
from drol import DRoL
import numpy as np

## Eg.1

In [2]:
from data import *
data = DataContainerSimu1(n=2000, N=20000)
data.generate_funcs_list(L=2, seed=0)
data.generate_data()

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target

In [3]:
drol = DRoL(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0)

In [4]:
drol.weight_

array([0.3760852, 0.6239148])

In [5]:
drol.predict()

{'pred': array([ 0.11257931, -0.25569903,  1.40225577, ..., -4.46150231,
         0.10331857,  1.47504082])}

In [6]:
drol = DRoL(f_learner='xgb', w_learner='linear')
drol.fit(Xlist,Ylist,X0)

In [7]:
drol.weight_

array([0.4583476, 0.5416524])

In [8]:
drol.predict()

{'pred': array([ 0.06606686, -0.45581428,  0.78326601, ..., -4.54084698,
        -0.15511154,  1.3716107 ])}

## Eg.2

In [9]:
import numpy as np
from scipy.stats import multivariate_normal

# Set random seed for reproducibility
np.random.seed(0)

# number of groups
L = 2
# dimension
p = 5

# mean vector for source
mean_source = np.zeros(p)



# Covariance matrix for source
cov_source = np.diag(np.ones(p))

# 1st group's source data
n1 = 2000
X1 = multivariate_normal.rvs(mean=mean_source, cov=cov_source, size=n1)
b1 = np.zeros(p)
b1[0:5] = np.array([1, -1, 0.5, 0., 0.]) + np.random.normal(size=5,loc=0,scale=0.1)
Y1 = X1**3 @ b1 + np.sin(X1.dot(b1)) + np.clip(np.exp(X1.dot(b1)),0,1) + np.random.normal(size=n1)

# 2nd group's source data
n2 = 2000
X2 = multivariate_normal.rvs(mean=mean_source, cov=cov_source, size=n2)
b2 = np.array([1, 0.5, -0.5, 0., 0.]) + np.random.normal(size=5,loc=0,scale=0.1)
Y2 = X2**3 @ b2 + np.sin(X2.dot(b2)) + np.clip(np.exp(X2.dot(b2)),0,1) + np.random.normal(size=n2)

# Target data with covariate shift
n0 = 20000
mean0 = np.zeros(p)
cov0 = np.copy(cov_source)


X0 = multivariate_normal.rvs(mean=mean0, cov=cov0, size=n0)
Xlist = [X1, X2]
Ylist = [Y1, Y2]


In [10]:
drol = DRoL(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0)

In [11]:
drol.weight_

array([0.44278977, 0.55721023])

In [12]:
drol.predict()

{'pred': array([ 1.8265214 , -2.17038101,  5.457425  , ...,  1.11140271,
        -0.37398075,  4.68917417])}

In [13]:
import numpy as np
from scipy.stats import multivariate_normal

# Set random seed for reproducibility
np.random.seed(0)

# number of groups
L = 2
# dimension
p = 5

# mean vector for source
mean_source = np.zeros(p)



# Covariance matrix for source
cov_source = np.diag(np.ones(p))

# 1st group's source data
n1 = 2000
X1 = multivariate_normal.rvs(mean=mean_source, cov=cov_source, size=n1)
b1 = np.zeros(p)
b1[0:5] = np.array([1, -1, 0.5, 0., 0.]) + np.random.normal(size=5,loc=0,scale=0.1)
Y1 = X1 @ b1  + np.random.normal(size=n1)

# 2nd group's source data
n2 = 2000
X2 = multivariate_normal.rvs(mean=mean_source, cov=cov_source, size=n2)
b2 = np.array([1, 0.5, -0.5, 0., 0.]) + np.random.normal(size=5,loc=0,scale=0.1)
Y2 = X2 @ b2 + np.random.normal(size=n2)

# Target data with covariate shift
n0 = 20000
mean0 = np.zeros(p)
cov0 = np.copy(cov_source)


X0 = multivariate_normal.rvs(mean=mean0, cov=cov0, size=n0)
Xlist = [X1, X2]
Ylist = [Y1, Y2]


In [14]:
drol = DRoL(f_learner='linear', w_learner='linear')
drol.fit(Xlist,Ylist,X0)

In [15]:
drol.weight_

array([0.40401335, 0.59598665])

In [16]:
drol.predict()

{'pred': array([ 0.61159652, -1.26197546,  1.53306672, ...,  0.35262114,
        -0.75045806,  1.57615709])}