# Examples

In [1]:
import numpy as np
from data import *  
from scipy.stats import multivariate_normal
import warnings
warnings.filterwarnings("ignore")

## Example 1: Linear Regression (Low-dimensional)

In [2]:
from Regression import linear

### Data Generating Process

In [3]:
# number of source groups = 3, with 100 samples each
# sigma: source group 1,3: 0.5; source group 2: 1
# target sample size = 100
# dimension p = 5
n_list = [100, 100, 100]
N = 1000  # target sample size
data = DataContainerSimu_linear_reg_lowd(n_list=n_list, N=N, p=5)
data.generate_funcs_list(seed=0)
data.generate_data(seed=0)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

In [4]:
reg = linear.lowd()
reg.fit(Xlist, Ylist, X0, loss_type='reward')
reg.infer()

In [5]:
reg.summary()

Model Summary:
Fitted Weights:

group     |        1        2        3
weight_   |   0.4929   0.3258   0.1813

Fitted Coefficients:

index     |        1        2        3        4        5
coef_     |  -0.0726  -0.0757   0.1073   0.0046   0.0573

Confidence Intervals for each coefficient:

index     |              1              2              3              4              5
CI        | (-0.2044,0.0592) (-0.2206,0.0691) (-0.0303,0.2448) (-0.1206,0.1297) (-0.0821,0.1967)



In [6]:
reg = linear.lowd()
reg.fit(Xlist, Ylist, X0, loss_type='squaredloss')
#reg.infer()

In [7]:
reg.summary()

Model Summary:
Fitted Weights:

group     |        1        2        3
weight_   |   0.1599   0.8401   0.0000

Fitted Coefficients:

index     |        1        2        3        4        5
coef_     |  -0.3644  -0.2584  -0.1271  -0.1144  -0.1266

Confidence Intervals not computed. Please run infer() method.


In [8]:
reg = linear.lowd()
reg.fit(Xlist, Ylist, X0, loss_type='regret')
#reg.infer()

In [9]:
reg.summary()

Model Summary:
Fitted Weights:

group     |        1        2        3
weight_   |   0.4472   0.4817   0.0710

Fitted Coefficients:

index     |        1        2        3        4        5
coef_     |  -0.1699  -0.1133   0.0364  -0.0109   0.0107

Confidence Intervals not computed. Please run infer() method.


## Example 2:Linear Regression (High-dimensionl)

### Data Generating Process

In [10]:
# two source groups, each with 100 samples, and 100 target samples
n_list = [100, 100]
N = 100

data = DataContainerSimu_linear_reg_highd(n_list=n_list, N=N, p=100)
data.generate_funcs_list(seed=0)
data.generate_data(seed=0)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

In [11]:
reg = linear.highd(verbose=True)
reg.fit(Xlist, Ylist, [1,5,10,98], X0=X0)
reg.infer(M=200, alpha=0.05, alpha_thres=0.01)

## time cost: 6.6s

Argument 'loading_intercept' set to False because intercept is False
start fitting-----
======> Bias Correction for initial estimators....
---> Computing for loading (1/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (2/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (3/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (4/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (1/4)...
The projection direction is identified at xi = 0.026710 at step = 6.0
---> Computing for loading (2/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (3/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (4/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
======> Bias 

In [12]:
reg.summary()

Model Summary:
Fitted Weights:

group     |        1        2
weight_   |   0.1825   0.8175

Fitted Plug-in Estimations:

index     |        1        5       10       98
coef_     |   0.0091   0.0932   0.1055   0.0417

Fitted Debiased Estimations:

index     |        1        5       10       98
coef_     |   0.3211   0.0141   0.0113   0.5321

Confidence Intervals for each coefficient:

index     |              1              5             10             98
CI        | (-0.1100,0.7522) (-0.4171,0.4453) (-0.5002,0.5229) (0.0419,1.0222)



### Prediction

In [13]:
reg.predict()

array([ 0.57445595, -0.02260501, -0.06851998,  0.11789731, -0.68551954,
       -0.52995015, -0.21396988,  0.14025542, -0.76298068,  1.12218245,
        0.44938959,  0.57412343, -0.37378568, -0.54137397,  0.34167318,
       -0.1521081 ,  0.19882123, -0.32239639, -0.81565754, -0.44871135,
       -0.30160634,  0.39700374,  1.03287672,  0.24744264, -0.5288435 ,
        0.90300083,  0.06967396,  0.04486066,  0.82883509,  0.03068964,
        0.01066929, -0.22267553,  0.32642271,  0.03653108, -0.81857478,
       -0.17895829, -0.34888221, -0.54606778, -0.37359128, -0.27869338,
       -0.00374357, -0.72312044,  0.63860943,  1.27726965,  0.00286989,
        0.04192286, -0.72136824, -0.17907397,  0.50076186,  0.28172247,
        0.19921625,  0.10110022,  0.56324557,  0.05519908, -1.04112279,
       -0.99421862,  0.33668741,  1.33077927, -1.28868999,  0.34215962,
        0.32227122,  0.20478748, -0.03070499,  0.55871012,  0.3965677 ,
       -0.50325759, -0.8164275 ,  0.45326108, -0.19556891,  0.00

## Example 3: Nonlinear Regression

In [14]:
from Regression import nonlinear

### Data Generating Process

In [15]:
# number of source groups = 3, each with 2000 samples, and 20000 target samples
# dimension p = 5
# sigma: source group 1,3: 0.5; source group 2: 2.
data = DataContainerSimu_Nonlinear_reg(n=2000, N=20000)
data.generate_funcs_list(L=3, seed=0)
data.generate_data()

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target

### Implementation \& Prediction

In [16]:
drol = nonlinear(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='reward')

## time cost: 8.7s

In [17]:
drol.weight_

array([0.20523537, 0.38031326, 0.41445137])

In [18]:
drol.predict()

array([-0.33094392, -0.21723839, -0.1624651 , ...,  1.33604095,
       -0.12983206,  1.42851897])

In [19]:
drol = nonlinear(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='squaredloss')

## time cost: 8.7s

In [20]:
drol.weight_

array([0.2562284 , 0.64085918, 0.10291242])

In [21]:
drol.predict()

array([-0.10840265, -0.50306315, -0.04315339, ...,  1.68323805,
        0.00388954,  0.51952304])

In [22]:
drol = nonlinear(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='regret')

## time cost: 8.7s

In [23]:
drol.weight_

array([0.44416422, 0.14679271, 0.40904307])

In [24]:
drol.predict()

array([-0.05722817, -0.30957706,  0.1766169 , ...,  0.52523496,
       -0.46829584,  1.40570068])

## Example 4: DRlm - Classification

In [25]:
from Classification import linear

### Data Generating Process

In [26]:
# two source groups, each with 100 samples, and 1000 target samples
n = 100; p = 5; L = 2; N = 1000; K = 2
data = DataContainerSimu_linear_Cl(n=n, N=N, p=p, L=L, K=K)
data.generate_funcs_list(seed=123)
data.generate_data(seed=123)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

In [27]:
cc = linear(f_learner='linear', w_learner='linear')
cc.fit(Xlist,Ylist,X0)
cc.infer()

## time cost: 4.8s

In [28]:
cc.summary()

Model Summary:
Fitted Weights:

group     |        1        2
weight_   |   0.7985   0.2015

Fitted Coefficients:

Class 1 coefficients:
index     |        1        2        3        4        5
coef_     |   0.0582  -0.1451  -0.0623  -0.0652   0.3645

Class 2 coefficients:
index     |        1        2        3        4        5
coef_     |   0.3192  -0.3334  -0.1658   0.3339  -0.3211

Confidence Intervals for each coefficient:

Class 1 Confidence Intervals:
index     |              1              2              3              4              5
CIs       | (-1.113,1.287) (-1.996,1.440) (-2.633,1.996) (-1.540,3.026) (-1.153,2.826)

Class 2 Confidence Intervals:
index     |              1              2              3              4              5
CIs       | (-0.866,1.729) (-2.148,1.004) (-2.503,1.806) (-1.280,3.821) (-1.507,1.776)



In [29]:
cc.summary(
    index = [3,5], class_index=2
)

Model Summary:
Fitted Weights:

group     |        1        2
weight_   |   0.7985   0.2015

Fitted Coefficients:

Class 2 coefficients:
index     |        3        5
coef_     |  -0.1658  -0.3211

Confidence Intervals for each coefficient:

Class 2 Confidence Intervals:
index     |              3              5
CIs       | (-2.503,1.806) (-1.507,1.776)



### Prediction

In [30]:
cc.predict_proba()

array([[0.46621458, 0.33948019, 0.19430523],
       [0.33735549, 0.3403033 , 0.32234121],
       [0.49823435, 0.25034083, 0.25142482],
       ...,
       [0.3513536 , 0.46685882, 0.18178758],
       [0.34266945, 0.52183562, 0.13549493],
       [0.27539232, 0.28251022, 0.44209746]])

In [31]:
cc.predict()

array([0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 2,
       0, 2, 0, 1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0, 0, 1, 1,
       1, 0, 2, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 2, 0, 1, 1,
       2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2,
       2, 2, 0, 0, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 0, 1, 1, 0, 1, 0,
       1, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1,
       2, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 0, 2, 1, 1, 2, 1, 2, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 1, 2, 0, 2, 0, 2, 2, 1, 0,
       0, 1, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2,
       2, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 2, 1, 2, 0, 2, 2, 0, 1, 0, 1, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       1, 2, 1, 2, 1, 1, 2, 1, 0, 1, 0, 2, 0, 0, 1, 2, 2, 2, 1, 0, 1, 2,
       2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2,