# Examples

In [47]:
import numpy as np
from data import *  
from geometry import *
from scipy.stats import multivariate_normal
import warnings
warnings.filterwarnings("ignore")

## Example 1: Linear Regression (Low-dimensional)

In [2]:
from Regression import linear

### Data Generating Process

In [3]:
# number of source groups = 3, with 1000 samples each
# sigma: source group 1,3: 0.5; source group 2: 2
# target sample size = 10000
# dimension p = 5
n_list = [1000, 1000, 1000]
N = 10000  # target sample size
data = DataContainerSimu_linear_reg_lowd(n_list=n_list, N=N, p=5)
data.generate_funcs_list(seed=0)
data.generate_data(seed=0)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

![Loss Types](loss_type.png)

In [4]:
reg = linear.ld()
reg.fit(Xlist, Ylist, X0, loss_type='reward')
reg.infer(alpha=0.05)

In [5]:
reg.summary()

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2        3
weight_   |   0.4567   0.3451   0.1982

Coefficient Estimators:

index     |        1        2        3        4        5
coef_     |  -0.0655  -0.0433   0.0032  -0.0018   0.0997

Confidence Intervals:

index     |              1              2              3              4              5
CI        | (-0.1283,-0.0027) (-0.1080,0.0214) (-0.0601,0.0665) (-0.0666,0.0629) (0.0351,0.1643)



In [6]:
pred = reg.predict()
print(pred[:10])

[-0.13644197 -0.08692431  0.04184841 -0.18107761 -0.30044671  0.0026928
 -0.30307077 -0.18239394 -0.06712825  0.20524958]


In [7]:
# Geometry view: the convex hull of the source coefficients (cloesest point to the origin)
beta_source = reg.beta_list
beta_ch, w_ch = nearest_on_convex_hull(beta_source)
print("Estimated coefficients on convex hull:", beta_ch)
print("Weights:", w_ch)

Estimated coefficients on convex hull: [-0.06592632 -0.0432436   0.00284681 -0.00168026  0.09944676]
Weights: [0.45700851 0.34576112 0.19723037]


In [8]:
reg = linear.ld()
reg.fit(Xlist, Ylist, X0, loss_type='squaredloss')
#reg.infer()

In [9]:
reg.summary()

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2        3
weight_   |   0.0000   1.0000   0.0000

Coefficient Estimators:

index     |        1        2        3        4        5
coef_     |  -0.3487  -0.1735  -0.2884  -0.1579  -0.1389

Confidence Intervals not computed. Please run infer() method.


In [10]:
pred = reg.predict()
print(pred[:10])

[-0.15697078  0.20275954 -0.30645405 -0.57685222 -0.10223598 -0.03202532
 -0.90429844  0.972492    1.15274749  0.42575315]


In [11]:
# Geometry view: the sufficiently large noise group dominates
reg.beta_list[1]

array([-0.34866929, -0.17351915, -0.2884043 , -0.15793023, -0.13894055])

In [12]:
reg = linear.ld()
reg.fit(Xlist, Ylist, X0, loss_type='regret')
#reg.infer()

In [13]:
reg.summary()

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2        3
weight_   |   0.3184   0.4467   0.2350

Coefficient Estimators:

index     |        1        2        3        4        5
coef_     |  -0.1004  -0.0816  -0.0368  -0.0537   0.0602

Confidence Intervals not computed. Please run infer() method.


In [14]:
pred = reg.predict()
print(pred[:10])

[-0.16569961  0.00258756 -0.03526818 -0.25353749 -0.30456777  0.02647563
 -0.39066011 -0.00236404  0.13115212  0.20484504]


In [15]:
# Geometry view: the center of the minimum enclosing ball of the source coefficients
beta_source = reg.beta_list
beta_cr, r_cr, w_cr = circumcenter_3vectors(beta_source)
print("Estimated coefficients on center of minimum enclosing ball:", beta_cr)
print("Weights:", w_cr)  

Estimated coefficients on center of minimum enclosing ball: [-0.09880893 -0.08368395 -0.03569643 -0.05683792  0.06023717]
Weights: [0.3107334  0.44558458 0.24368202]


## Example 2:Linear Regression (High-dimensionl)

### Data Generating Process

In [16]:
# two source groups, each with 100 samples, and 100 target samples
n_list = [100, 100]
N = 100

data = DataContainerSimu_linear_reg_highd(n_list=n_list, N=N, p=100)
data.generate_funcs_list(seed=0)
data.generate_data(seed=0)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

In [17]:
reg = linear.hd(verbose=True)
reg.fit(Xlist, Ylist, [1,5,10,98], X0=X0)
reg.infer(M=200, alpha=0.05, alpha_thres=0.01)

## time cost: 6.6s

Argument 'loading_intercept' set to False because intercept is False
start fitting-----
======> Bias Correction for initial estimators....
---> Computing for loading (1/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (2/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (3/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (4/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (1/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (2/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
---> Computing for loading (3/4)...
The projection direction is identified at xi = 0.060097 at step = 4.0
---> Computing for loading (4/4)...
The projection direction is identified at xi = 0.040065 at step = 5.0
======> Bias 

In [18]:
reg.summary()

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2
weight_   |   0.1574   0.8426

Plug-in Estimators:

index     |        1        5       10       98
coef_     |   0.0079   0.0803   0.1087   0.0359

Debiased Estimators:

index     |        1        5       10       98
coef_     |   0.2073  -0.0132   0.0497   0.5338

Confidence Intervals:

index     |              1              5             10             98
CI        | (-0.1542,0.5687) (-0.4427,0.4164) (-0.3308,0.4301) (0.0375,1.0301)



### Prediction

In [19]:
pred = reg.predict()
print(pred[:10])

[ 0.5931408   0.01983438 -0.12045868  0.12917504 -0.68239194 -0.49449755
 -0.18172753  0.15242893 -0.76921899  1.13411843]


## Example 3: Machine Learning Regression

In [48]:
from Regression import ml

### Data Generating Process

In [49]:
# number of source groups = 3, each with 10000 samples, and 100000 target samples
# dimension p = 5
# sigma: source group 1,3: 0.5; source group 2: 3.
data = DataContainerSimu_Nonlinear_reg(n=10000, N=100000)
data.generate_funcs_list(L=3, seed=0)
data.generate_data()

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target

### Implementation \& Prediction

In [50]:
drol = ml(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='reward')

## time cost: 8.7s

In [51]:
drol.weight_

array([0.23619293, 0.29104051, 0.47276655])

In [52]:
drol.predict()

array([-1.37911566, -1.01748387,  1.44855369, ..., -1.79589733,
       -0.42999676,  2.98552634])

In [53]:
# Geometry view: the convex hull of the source coefficients (cloesest point to the origin)
pred_source = drol.pred_full_mat.T
pred_ch, w_ch = nearest_on_convex_hull(pred_source)
print("Predictions on convex hull:", pred_ch)
print("Weights:", w_ch)


Predictions on convex hull: [-1.38436167 -1.00976801  1.47364845 ... -1.81097766 -0.44569888
  2.96259133]
Weights: [0.23864968 0.28245441 0.4788959 ]


In [54]:
drol = ml(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='squaredloss')

## time cost: 8.7s

In [55]:
drol.weight_

array([0., 1., 0.])

In [56]:
drol.predict()

array([-0.8600474 , -1.5655055 , -0.60189897, ..., -0.58915877,
        0.9634735 ,  5.21788502])

In [57]:
# Geometry view: the sufficiently large noise group dominates
pred_source = drol.pred_full_mat.T
pred_source[1]

array([-0.8600474 , -1.5655055 , -0.60189897, ..., -0.58915877,
        0.9634735 ,  5.21788502])

In [58]:
drol = ml(f_learner='xgb', w_learner='kliep')
drol.fit(Xlist,Ylist,X0, loss_type='regret')

## time cost: 8.7s

In [59]:
drol.weight_

array([0.41122666, 0.21230474, 0.3764686 ])

In [60]:
drol.predict()

array([-1.82018649, -1.35423715,  1.57969483, ..., -1.75827626,
       -1.01742939,  1.22626068])

In [33]:
# Geometry view: the center of the minimum enclosing ball of the source coefficients
pred_source = drol.pred_full_mat.T
pred_cr, r_cr, w_cr = circumcenter_3vectors(pred_source)
print("Predictions on center of minimum enclosing ball:", pred_cr)
print("Weights:", w_cr)

Predictions on center of minimum enclosing ball: [ 1.19534202 -0.7734592   0.13471152 ...  1.21178966  0.54131003
 -0.07881488]
Weights: [0.39353541 0.26546146 0.34100313]


## Example 4: DRlm - Classification

In [34]:
from Classification import Classification

### Data Generating Process

In [35]:
# two source groups, each with 100 samples, and 1000 target samples
n = 100; p = 5; L = 2; N = 1000; K = 2
data = DataContainerSimu_linear_Cl(n=n, N=N, p=p, L=L, K=K)
data.generate_funcs_list(seed=123)
data.generate_data(seed=123)

Xlist = data.X_sources_list
Ylist = data.Y_sources_list
X0 = data.X_target


### Implementation \& Results

In [36]:
cc = Classification(f_learner='linear', w_learner='linear')
cc.fit(Xlist,Ylist,X0)
cc.infer()

## time cost: 4.8s

In [37]:
cc.summary()

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2
weight_   |   0.7985   0.2015

Coefficient Estimators:

Class 1 coefficients:
index     |        1        2        3        4        5
coef_     |   0.0582  -0.1451  -0.0623  -0.0652   0.3645

Class 2 coefficients:
index     |        1        2        3        4        5
coef_     |   0.3192  -0.3334  -0.1658   0.3339  -0.3211

Confidence Intervals:

Class 1 Confidence Intervals:
index     |              1              2              3              4              5
CIs       | (-1.113,1.287) (-1.996,1.440) (-2.633,1.996) (-1.540,3.026) (-1.153,2.826)

Class 2 Confidence Intervals:
index     |              1              2              3              4              5
CIs       | (-0.866,1.729) (-2.148,1.004) (-2.503,1.806) (-1.280,3.821) (-1.507,1.776)



In [38]:
cc.summary(
    index = [3,5], class_index=2
)

Model Summary:
CGDRO Aggregated Weights:

group     |        1        2
weight_   |   0.7985   0.2015

Coefficient Estimators:

Class 2 coefficients:
index     |        3        5
coef_     |  -0.1658  -0.3211

Confidence Intervals:

Class 2 Confidence Intervals:
index     |              3              5
CIs       | (-2.503,1.806) (-1.507,1.776)



### Prediction

In [39]:
pred_proba = cc.predict_proba()
print(pred_proba[:10, :])

[[0.46621458 0.33948019 0.19430523]
 [0.33735549 0.3403033  0.32234121]
 [0.49823435 0.25034083 0.25142482]
 [0.37073523 0.32970061 0.29956415]
 [0.24311714 0.18835182 0.56853105]
 [0.32211245 0.18882565 0.4890619 ]
 [0.4418154  0.42461165 0.13357295]
 [0.45198723 0.42602329 0.12198948]
 [0.36234295 0.34360026 0.29405679]
 [0.39832987 0.46336429 0.13830584]]


In [40]:
pred = cc.predict()
print(pred[:10])

[0 1 0 0 2 2 0 0 0 1]
